const CONFIG={ROOT:'Silsilah Keluarga',PHOTO:'Foto Anggota',SS:'Database Silsilah Keluarga',MEM:'Anggota',SPOUSE:'Pasangan'};
function doGet(){return HtmlService.createTemplateFromFile('index').evaluate().setTitle('Silsilah Keluarga').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function include(n){return HtmlService.createHtmlOutputFromFile(n).getContent()}
function setupDatabase(){const root=getFolder_(CONFIG.ROOT), photo=getSub_(root,CONFIG.PHOTO);let ss;const f=root.getFilesByName(CONFIG.SS);if(f.hasNext())ss=SpreadsheetApp.open(f.next());else{ss=SpreadsheetApp.create(CONFIG.SS);DriveApp.getFileById(ss.getId()).moveTo(root)};sheet_(ss,CONFIG.MEM,['id','nama','jenis_kelamin','orang_tua_id','anak_ke','status_hidup','tanggal_wafat','bio','foto_url','generasi','aktif','created_at','updated_at']);sheet_(ss,CONFIG.SPOUSE,['id','anggota_id','nama_pasangan','urutan','status_hubungan','created_at','updated_at']);PropertiesService.getScriptProperties().setProperties({SPREADSHEET_ID:ss.getId(),PHOTO_FOLDER_ID:photo.getId()});return {ok:true,spreadsheet:ss.getUrl(),folder:root.getUrl(),photos:photo.getUrl()}}
function getData(){const ss=db_(),m=read_(ss,CONFIG.MEM),s=read_(ss,CONFIG.SPOUSE),map={};s.forEach(x=>(map[x.anggota_id]??=[]).push(x));m.forEach(x=>x.pasangan=(map[x.id]||[]).sort((a,b)=>(+a.urutan||0)-(+b.urutan||0)));return {ok:true,members:m.filter(x=>String(x.aktif)!=='false')}}
function addMember(d){const id=d.id||Utilities.getUuid(),n=new Date();db_().getSheetByName(CONFIG.MEM).appendRow([id,d.nama||'',d.jenis_kelamin||'',d.orang_tua_id||'',d.anak_ke||'',d.status_hidup||'Hidup',d.tanggal_wafat||'',d.bio||'',d.foto_url||'',d.generasi||'',true,n,n]);return {ok:true,id}}
function addSpouse(d){db_().getSheetByName(CONFIG.SPOUSE).appendRow([d.id||Utilities.getUuid(),d.anggota_id||'',d.nama_pasangan||'',d.urutan||1,d.status_hubungan||'Menikah',new Date(),new Date()]);return {ok:true}}
function sheet_(ss,n,h){let sh=ss.getSheetByName(n)||ss.insertSheet(n);sh.getRange(1,1,1,h.length).setValues([h]);sh.setFrozenRows(1)}
function read_(ss,n){const sh=ss.getSheetByName(n);if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v.shift();return v.filter(r=>r.some(x=>x!=='')).map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i] instanceof Date?r[i].toISOString():r[i]);return o})}
function db_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw Error('Database belum dibuat. Jalankan setupDatabase() sekali.');return SpreadsheetApp.openById(id)}
function getFolder_(n){const i=DriveApp.getFoldersByName(n);return i.hasNext()?i.next():DriveApp.createFolder(n)}
function getSub_(p,n){const i=p.getFoldersByName(n);return i.hasNext()?i.next():p.createFolder(n)}
